<?php

use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;

?>

<div class="btn-toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-list"></span> <?php $this->show('Menu'); ?> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
         <li><a href="<?php echo $this->url('Videogallery:Admin:File:Add@indexAction'); ?>"><i class="glyphicon glyphicon-facetime-video"></i> <?php $this->show('Upload new file'); ?></a></li>
         <li><a href="<?php echo $this->url('Videogallery:Admin:Category:Add@indexAction'); ?>"><i class="glyphicon glyphicon-book"></i> <?php $this->show('Add new category'); ?></a></li>
         <li class="divider"></li>
         <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li><a href="#" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
      </ul>
    </div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Video-gallery')); ?>

<form>
    
    <div class="row">
    
        <div class="col-lg-7">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>
                                <?php if (!empty($files)): ?>
                                <input type="checkbox" />
                                <?php endif; ?>
                            </th>
                            <th><?php $this->show('#'); ?></th>
                            <th><?php $this->show('Title'); ?></th>
                            <th><?php $this->show('Default'); ?></th>
                            <th><?php $this->show('SEO Enabled'); ?></th>
                            <th><?php $this->show('Actions'); ?></th>
                        </tr>
                    </thead>
                    <?php if (!empty($files)): ?>
                    
                    <tbody>
                        <?php foreach ($files as $file): ?>
                        <tr>
                            <td>
                                <input type="checkbox" name="toDelete[<?php echo $file->getId(); ?>]" />
                            </td>
                            <td><?php echo $file->getId(); ?></td>
                            <td><?php echo $file->getTitle(); ?></td>
                            <td>
                                <?php echo Element::radio('default', $file->getId(), $file->getDefault()); ?>
                            </td>
                            <td>
                                <?php echo Element::checkbox(sprintf('seo[%s]', $file->getId()), $file->getSeo()); ?>
                            </td>
                            <td>
                                <a class="view" href="<?php echo $file->getUrl(); ?>"></a>
                                <a class="edit" href="<?php echo $this->url('Videogallery:Admin:File:Edit@indexAction', $file->getId()); ?>"></a>
                                <a class="delete" href="#" data-id="<?php echo $file->getId(); ?>"></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <?php endif; ?>
                    
                </table>
            </div>
        </div>
    
    <div class="col-lg-5">
        <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
        <table class="table table-hover table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center"><?php $this->show('#'); ?></th>
                    <th class="text-center"><?php $this->show('Name'); ?></th>
                    <th class="text-center"><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>
            
            <?php if (!empty($categories)): ?>
            <tbody>
                <?php foreach ($categories as $id => $category): ?>
                
                <tr <?php HtmlHelper::addClassOnDemand(isset($categoryId) && $categoryId == $id, 'info'); ?>>
                    <td class="text-center text-muted"><?php echo $id; ?></td>
                    <td>
                        <a class="pull-left" href="<?php echo $this->url('Videogallery:Admin:Browser@categoryAction', $id); ?>">
                            <?php HtmlHelper::wrapOnDemand(isset($categoryId) && $categoryId == $id, 'strong', $category); ?>
                        </a>
                    </td>
                    <td class="text-center">
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this category'); ?>" data-button="edit" href="<?php echo $this->url('Videogallery:Admin:Category:Edit@indexAction', $id); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this category'); ?>" data-button="delete" data-button="delete" data-category="category" data-id="<?php echo $id; ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <?php endif; ?>
        </table>
        
        <?php if (empty($categories)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
        </div>
        <?php endif; ?>
        
    </div>
    
    </div>
    
</form>

<?php $this->loadBlock('paginator'); ?>
