
<div class="btn-toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Menu'); ?>
        <span class="caret"></span>
      </button> 
      <ul class="dropdown-menu">
         <li><a href="#"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add new file'); ?></a></li>
         <li><a href="#"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add category'); ?></a></li>
         <li class="divider"></li>
         <li><a href="#" id="save-changes-btn"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li><a href="#" id="remove-selected-btn" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
      </ul>
    </div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Video-gallery')); ?>

<form>
    <table class="list table-hover">
        <thead>
            <tr>
                <th><input type="checkbox" /></th>
                <th><?php $this->show('#'); ?></th>
                <th><?php $this->show('Title'); ?></th>
                <th><?php $this->show('Default'); ?></th>
                <th><?php $this->show('SEO Enabled'); ?></th>
                <th><?php $this->show('Actions'); ?></th>
            </tr>
        </thead>
        
        <?php if (!empty($pages)): ?>
        
        <tbody>
            
            <?php foreach ($pages as $page): ?>
            <tr>
                <td><input type="checkbox" name="toDelete[<?php echo $page->id; ?>]" /></td>
                <td><?php echo $page->id; ?></td>
                <td><?php echo $page->title; ?></td>
                <td>
                    <?php if ($page->default): ?>
                    <input type="radio" name="default" value="<?php echo $page->id; ?>" checked="checked" />
                    
                    <?php else: ?>
                    <input type="radio" name="default" value="<?php echo $page->id; ?>" />
                    
                    <?php endif; ?>
                </td>
                
                <td>
                    <input type="hidden" name="seo[<?php echo $page->id; ?>]" value="0" />
                    
                    <?php if ($page->seoEnabled): ?>
                    <input type="checkbox" name="seo[<?php echo $page->id; ?>]" value="1" checked="checked" />
                    
                    <?php else: ?>
                    <input type="checkbox" name="seo[<?php echo $page->id; ?>]" value="1" checked="checked" />
                    
                    <?php endif; ?>
                </td>
                
                <td>
                    <a class="view" href="<?php printf('/%s/', $page->slug); ?>"></a>
                    <a class="edit" href="<?php printf('/admin/module/pages/edit/%s', $page->id); ?>"></a>
                    <a class="delete" href="#" data-id="<?php echo $page->id; ?>"></a>
                </td>
            </tr>
            <?php endforeach; ?>
            
        </tbody>
        <?php endif; ?>
        
    </table>
</form>

<?php $this->loadBlock('paginator'); ?>
