<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<form data-group="category">
    <div class="well clearfix">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('category[title]', $category->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Type category title'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>

        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Parent category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('category[parent_id]', $categories, $category->getParentId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::textarea('category[description]', $category->getDescription(), array('data-wysiwyg' => 'true')); ?>
            </div>
        </div>
        
        <div class="options">
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('category[seo]', $category->getSeo(), array('class' => 'form-control')) ?>
                </div>
            </div>

            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('category[slug]', $category->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this category. By default is taken from a title'))); ?>
                        <span class="input-group-addon">
                            <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                        </span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('category[keywords]', $category->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::textarea('category[meta_description]', $category->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                </div>
            </div>
            
        </div>
    </div>
    
    <?php if (!$category->getId()): ?>
    
    <button data-button="add" data-back-url="<?php echo $this->url('Videogallery:Admin:Category@editAction', null); ?>" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-toggle="add-create" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
    
    <?php else: ?>
    
    <button data-button="save" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-toggle="save-create" data-back-url="<?php echo $this->url('Videogallery:Admin:Category@addAction'); ?>" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
    
    <?php endif; ?>
    
    <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
    <button data-button="cancel" data-url="<?php echo $this->url('Videogallery:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
