<?php

use Krystal\Form\Element;

?>

<form data-group="category">
    <div class="well clearfix">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('category[title]', $category->getTitle(), array('class' => 'form-control', 'placeholder' => 'Type category title')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>

        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Parent category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('category[parent_id]', $categories, $category->getParentId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::textarea('category[description]', $category->getDescription(), array('data-wysiwyg' => 'true')); ?>
            </div>
        </div>
    </div>
    
    <?php if (!$category->getId()): ?>
    
    <button data-button="add" data-back-url="<?php echo $this->url('Videogallery:Admin:Category@editAction', null); ?>" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-toggle="add-create" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
    
    <?php else: ?>
    
    <button data-button="save" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-toggle="save-create" data-back-url="<?php echo $this->url('Videogallery:Admin:Category@addAction'); ?>" data-url="<?php echo $this->url('Videogallery:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
    
    <?php endif; ?>
    
    <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
    <button data-button="cancel" data-url="<?php echo $this->url('Videogallery:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
