<?php

use Krystal\Form\Element;

?>

<form data-group="video">
    <?php echo Element::hidden('video[id]', $video->getId()); ?>
    
    <div class="well clearfix">
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('video[title]', $video->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Video title'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>

        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('video[category_id]', $categories, $video->getCategoryId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::textarea('video[description]', $video->getDescription(), array('data-wysiwyg' => 'true')); ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Image cover'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::file('imageFile'); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Video file'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::file('videoFile'); ?>
            </div>
        </div>
        
        <div class="options">
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('video[seo]', $video->getSeo(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('video[published]', $video->getPublished(), array('class' => 'form-control')); ?>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('video[order]', $video->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Order of this video file to be displayed in a category'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('URL slug'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('video[slug]', $video->getSlug(), array('class' => 'form-control', 'placeholder' => $this->translate('URL slug for this page. By default is taken from a title'))); ?>
                        <span class="input-group-addon">
                            <a href="#" id="slug-btn">
                                <i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('video[keywords]', $video->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::textarea('video[meta_description]', $video->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                </div>
            </div>
        </div>
    </div>
    
    <?php if (!$video->getId()): ?>
    
    <button data-button="add" data-back-url="<?php echo $this->url('Videogallery:Admin:File@editAction', null); ?>" data-url="<?php echo $this->url('Videogallery:Admin:File@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-toggle="add-create" data-url="<?php echo $this->url('Videogallery:Admin:File@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Upload new'); ?></button>
    
    <?php else: ?>
    
    <button data-button="save" data-url="<?php echo $this->url('Videogallery:Admin:File@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-toggle="save-create" data-back-url="<?php echo $this->url('Videogallery:Admin:File@addAction'); ?>" data-url="<?php echo $this->url('Videogallery:Admin:File@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Upload new'); ?></button>
    
    <?php endif; ?>
    
    <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
    <button data-button="cancel" data-url="<?php echo $this->url('Videogallery:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
