<?php $this->loadBlock('start'); ?>

<main>
	
	<?php $this->loadBlock('breadcrumbs'); ?>
	<?php $this->loadBlock('flash'); ?>
	
	<form>
		<div class="well clearfix">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Title'); ?><b>*</b></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="text" name="title" class="form-control" placeholder="<?php $this->show('Page title'); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Image cover'); ?></label>
				<div class="col-lg-10">
					<input type="file" name="imageFile" />
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Video file'); ?></label>
				<div class="col-lg-10">
					<input type="file" name="videoFile" />
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
				<div class="col-lg-10">
					<textarea name="description" rows="7" class="form-control"></textarea>
				</div>
			</div>
			
			
			
			<div class="options">
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
					<div class="col-lg-10">
						<input type="text" class="form-control" name="order" placeholder="<?php $this->show('Order of the video file to be displayed in category'); ?>" />
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
					<div class="col-lg-10">
						<input type="hidden" name="seoEnabled" value="0" />
						<input type="checkbox" name="seoEnabled" value="1" checked="checked" class="form-control" />
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('URL slug'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="slug" class="form-control" placeholder="<?php $this->show('URL slug for this page. By default is taken from a title'); ?>" />
							<span class="input-group-addon">
								<a href="#" id="slug-btn">
									<i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i>
								</a>
							</span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="keywords" class="form-control" placeholder="<?php $this->show('Keywords used for search engines'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<textarea name="metaDescription" class="form-control" placeholder="<?php $this->show('Meta description for search engines'); ?>"></textarea>
					</div>
				</div>
				
			</div>
		</div>
		
		<?php if (isset($editing)): ?>
		
		<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
		<button data-toggle="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
		
		<?php else: ?>
		
		
		<?php endif; ?>
		
		<button data-button="options" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> <?php $this->show('More options'); ?></button>
		<button data-button="cancel" class="btn btn-default"><span class="glyphicon glyphicon-floppy-remove"></span> <?php $this->show('Cancel'); ?></button>
		
	</form>
	
</main>

<?php $this->loadBlock('end'); ?>
